export const OBTER_PROJETOS = "OBTER_PROJETOS";
export const CADASTRAR_PROJETO = "CADASTRAR_PROJETO";
export const ALTERAR_PROJETO_API = "ALTERAR_PROJETO_API";
export const REMOVER_PROJETO_API = "REMOVER_PROJETO_API";

export const OBTER_TAREFAS = "OBTER_TAREFAS";
export const CADASTRAR_TAREFA = "CADASTRAR_TAREFA";
export const ALTERAR_TAREFA_API = "ALTERAR_TAREFA_API";
