export const OBTER_PROJETOS = "OBTER_PROJETOS";
export const CADASTRAR_PROJETO = "CADASTRAR_PROJETO";
export const ALTERAR_PROJETO_API = "ALTERAR_PROJETO_API";
export const REMOVER_PROJETO_API = "REMOVER_PROJETO_API";